### PR TITLE
support node renaming

### PR DESCRIPTION
**Pull request by mariakleiner**

### CODE REVIEW

**Comment by mariakleiner** [comment]
i haven't figured out yet how to make the current node name automatically selected... will keep iterating.

**Comment by sjmiles** [comment]
> Normally you can call input.focus() and/or input.selectAll(), but you cannot invoke methods from Particle-space. I know we've handled this in the past, but I will have to do some archaeology.

Ok, so none of that applies to your actual problem, sorry. I read the commit more closely the 2nd time.

Content-editable is a really big hammer, we probably can just use an <input>.

**Review by sjmiles — APPROVED** [review]

**Comment by mariakleiner** [comment]
> > Normally you can call input.focus() and/or input.selectAll(), but you cannot invoke methods from Particle-space. I know we've handled this in the past, but I will have to do some archaeology.
> 
> Ok, so none of that applies to your actual problem, sorry. I read the commit more closely the 2nd time.
> 
> Content-editable is a really big hammer, we probably can just use an <input>.

Addressed the comment (sorry, i originally looked at it in gmail and it didn't show `<input>`, just the dot)...
(Something weird happened to git during pull and now this has a lot more changes than needed, i can try to fix it later, but does the latest commit look right?)

**Comment by sjmiles** [comment]
Compare to https://github.com/project-oak/arcsjs-core/pull/197?

I couldn't figure out if this is right from looking at the files, so I took your PR and undid the merge-with-main part. Is that even better?!?

**Pull request closed without merging**
