### PR TITLE
Audio node support (take 2)

### PR DESCRIPTION
**Pull request by mariakleiner**
Audio and video together:
https://screencast.googleplex.com/cast/NTkzODg2OTA3MDQ2Mjk3NnxjNmFhOTE1NS0zZA

### CODE REVIEW

**Comment by mariakleiner** [comment]
The only thing that I noticed here is that if the selected graph turns video on, and then is deleted, there video remains on, and there is no UI to turn it off. I'll need to add some cleanup to the Graph management, if we decide to go on with this approach.

**Review by sjmiles — APPROVED** [review]
Great!

**Comment by sjmiles** [comment]
> The only thing that I noticed here is that if the selected graph turns video on, and then is deleted, there video remains on, and there is no UI to turn it off. I'll need to add some cleanup to the Graph management, if we decide to go on with this approach.

Interesting. Will consider!

**Comment by mariakleiner** [comment]
> > The only thing that I noticed here is that if the selected graph turns video on, and then is deleted, there video remains on, and there is no UI to turn it off. I'll need to add some cleanup to the Graph management, if we decide to go on with this approach.
> 
> Interesting. Will consider!

i will send a follow up PR shortly. meantime i noticed that the GraphToolbar is completely broken, will fix it next.

**Pull request merged**
