### PR TITLE
refactor connection / non-connection properties in Inspector

### PR DESCRIPTION
**Pull request by mariakleiner**

### CODE REVIEW

**Comment by mariakleiner** [comment]
the implementation is a bit weird... let's discuss...
now that i'm thinking about it, maybe, node having both - `props` and `connections` is wrong, maybe it should be a single:

`
props: {
    value: ...,
    connection: [...],
 }
`
instead.
it would be inspected more naturally for sure, and just in general a more data focused structure. WDYT?

**Review by sjmiles — APPROVED** [review]
🎉

**Comment by sjmiles** [comment]
> the implementation is a bit weird... let's discuss... now that i'm thinking about it, maybe, node having both - `props` and `connections` is wrong, maybe it should be a single:
> 
> `props: { value: ..., connection: [...], }` instead. it would be inspected more naturally for sure, and just in general a more data focused structure. WDYT?

Sounds right, nice insight.

**Comment by mariakleiner** [comment]
> > the implementation is a bit weird... let's discuss... now that i'm thinking about it, maybe, node having both - `props` and `connections` is wrong, maybe it should be a single:
> > `props: { value: ..., connection: [...], }` instead. it would be inspected more naturally for sure, and just in general a more data focused structure. WDYT?
> 
> Sounds right, nice insight.

I'll submit this now (I played with it a bit, sometimes the default check/unchecked connected behaves weirdly, but harmless, hopefully it is not too broken) and work on refactoring the `props` and `connections` (unless i hear otherwise from you)

**Pull request merged**
